### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wtbarnes** [uwsampa/research-group-web#2]
This is a great template and thanks for making it available to the public. How is it licensed? Are users free to use and modify it as they see fit (with proper attribution of course)? It may be a good idea to include a LICENSE file in the repo.

**Comment by iyzhang** [comment]
It is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](https://creativecommons.org/licenses/by-nc/4.0/), as noted in the README, which allows non-commercial modification.

**Comment by wtbarnes** [comment]
Ah sorry must've missed it in the README. Thanks for the clarification!

**Comment by sampsyo** [comment]
Thanks, Irene! I added a license file too, just for fun.
