### ISSUE TITLE
upstream pull no longer works with git:// address

### ISSUE THREAD

**Issue by ljschumacher** [uwsampa/research-group-web#23]
using the upstream address as described in the readme no longer works, seemingly due to changes in github security protocols

git pull upstream master
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by sampsyo** [comment]
Thanks! Switched to an HTTPS URL.
